const express = require('express');
const routes = require('./routes/index');
const path = require('path');
const User = require('./user');
const Room = require('./room');
const app = express();
const server = require('http').Server(app);
const io = require('socket.io')(server);
app.use('/api', routes);
server.listen(process.env.PORT || 3000);
